theme: jekyll-theme-minimal
# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://gcdunn.github.io"
baseurl: ""
title: [Glenna Dunn]
description: [Astrophysics PhD Student at Vanderbilt University]